### ISSUE TITLE
Internal Server Error when a source page is Archived

### ISSUE THREAD

**Issue by zhanglian77** [silverstripe-labs/silverstripe-externallinks#71]
When there is an existing report, then archive the page where the external link is on, and click "Reports -> External broken links report" again, it shows an "Internal Server Error". The error message is: 

`[Emergency] Uncaught Error: Call to a member function CMSEditLink() on null
GET /admin/reports/show/SilverStripe-ExternalLinks-Reports-BrokenExternalLinksReport
Line 52 in /vendor/silverstripe/externallinks/src/Reports/BrokenExternalLinksReport.php`

**Notes**

It can be fixed by adding "if ($page)" condition on line 50 in BrokenExternalLinksReport.php

**Comment by Cheddam** [comment]
Increasing impact rating, as this bug renders the functionality of the module inoperable if triggered.

**Comment by brynwhyman** [comment]
Fixed in https://github.com/silverstripe/silverstripe-externallinks/pull/72
