### ISSUE TITLE
4.11.0-beta1 PHP 8.1 - Broken links do not show in broken external links report

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe-labs/silverstripe-externallinks#79]
Report button works, queuedjobs works fine, link has a red background in tinymce, however broken link doesn't show in the report itself 

This is possibly a permission error, I was running a non-admin in a group with every permission checkbox checked (excluding "Access to all CMS sections" (instead I ticked access each section individually) and "Full administrative rights")

**Comment by emteknetnz** [comment]
Duplicate - PR to fix was recently merged - https://github.com/silverstripe/silverstripe-externallinks/pull/78

**Comment by GuySartorelli** [comment]
@emteknetnz Should this ticket be closed since the fix was merged? Or is there some action still required for this issue?
