### ISSUE TITLE
Checking for broken links in arbitrary rich text fields (for example, in data objects)

### ISSUE THREAD

**Issue by rob-mcgrail** [silverstripe-labs/silverstripe-externallinks#85]
Is there a way to coerce this report into checking fields on data objects? 

Seems like it would be a useful configuration option, but is it possible at all?

**Comment by GuySartorelli** [comment]
Currently this module only tracks broken external links from `HTMLText` db fields in `SiteTree` objects.
There's an [open issue](https://github.com/silverstripe/silverstripe-externallinks/issues/68) for reporting on broken external links for elemental blocks which would likely involve allowing arbitrary `DataObject` classes to add themselves to the report.
