### ISSUE TITLE
CMS 5 - Report button is unresponsive

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe-labs/silverstripe-externallinks#91]
Discovered as part of 5.0.0 beta testing

When I click "Create new report" basically nothing happens

When I refresh the page, then I can see the broken link in the report. However it shows an HTTP ERROR CODE of "0" (Server Not Available) instead of "503" (Service Unavailable) which is what is it used to for CMS 4.  It probably should just be 404.

## Acceptance criteria
- Clicking the "create"  button provides meaningful feedback to the user.
- Correct status code of failed external link validation is recorded.

## PRs
- https://github.com/silverstripe/silverstripe-externallinks/pull/93

**Comment by GuySartorelli** [comment]
PR merged
