### ISSUE TITLE
"Create new report" button is disabled. Instead of "Create new report" title it presents loading spinner. 

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe-labs/silverstripe-externallinks#94]
## Description
Regression tests have been executed on: SC PHP 7.4 Chrome GraphQL v3 Sink
User cannot click button "Create new report". Button is disabled and shows spinner instead of button title. 
This problem was fixed for CMS 5 : 
 - https://github.com/silverstripe/silverstripe-externallinks/pull/93

### Steps to reproduce
- I go to the Reports administration section
- I click External broken links report
- I click Create new report (disabled, loading)

## AC's
- [x] If server returns error or empty response, button should get back to its initial state with title 'Create new report' 
## PR
- https://github.com/silverstripe/silverstripe-externallinks/pull/96

**Comment by GuySartorelli** [comment]
Merged
